$schema: "https://json-schema.org/draft/2020-12/schema"
title: Contract Risk Policy
type: object
required: [name, version, rules]
properties:
  name:
    type: string
  version:
    type: string
  description:
    type: string
  rules:
    type: array
    minItems: 1
    items:
      type: object
      required: [id, description, severity, pattern]
      properties:
        id:
          type: string
        description:
          type: string
        severity:
          type: string
          enum: [low, medium, high, critical]
        tags:
          type: array
          items: { type: string }
        pattern:
          oneOf:
            - type: string
            - type: array
              items: { type: string }
        examples:
          type: array
          items: { type: string }
